version: "3.7"
services:        
  dockerproxy:
   image: tecnativa/docker-socket-proxy:arm32v7 
   #privileged: true
   ports:
     - 2375
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
   environment:
    - LOG_LEVEL=debug
    - CONTAINERS=1
   networks:
      - traefik

networks:
  traefik:
    external: true
