# https://github.com/shoenig/ssh-key-sync
- name: Create keys dir
  file:
    path: /opt/keys
    state: directory

- name: Generate config json
  template:
    src:  files/config.json.tmpl
    dest: /opt/keys/config.json

- name: copy service file
  copy:
    src: files/Dockerfile
    dest: /opt/keys/Dockerfile

- name: compile binary
  command: docker build -t ssh-key-sync /opt/keys/

- name: create binary
  command: docker run --name ssh-key-sync ssh-key-sync

- name: retrieve binary
  command: docker cp ssh-key-sync:/go/bin/ssh-key-sync /opt/keys/ssh-key-sync

- name: cleanup
  command: docker image rm golang:1.13-stretch

- name: cleanup
  command: docker image rm ssh-key-sync:latest
  
- name: copy service file
  copy:
    src: files/ssh-key-sync.service
    dest: /etc/systemd/system/ssh-key-sync.service

- name: copy timer file
  copy:
    src: files/ssh-key-sync.timer
    dest: /etc/systemd/system/ssh-key-sync.timer

- name: enable a timer for ssh key sync
  systemd:
    name: ssh-key-sync.timer
    state: started
    enabled: yes