# https://wiki.odroid.com/odroid-xu4/software/building_kernel
- apt:
    pkg:
      - git 
      - gcc 
      - g++ 
      - build-essential 
      - libssl-dev 
      - bc

- git:
    repo: 'https://github.com/hardkernel/linux.git'
    dest: /tmp/linux
    version: odroid-5.4.y
    depth: 1

- name: Update kernel and Device Tree Blob
  shell: |
    cd /tmp/linux
    make odroidxu4_defconfig
    make -j8
    sudo make modules_install
    sudo cp -f arch/arm/boot/zImage /media/boot
    sudo cp -f arch/arm/boot/dts/exynos5422-odroidxu3.dtb /media/boot
    sudo cp -f arch/arm/boot/dts/exynos5422-odroidxu4.dtb /media/boot
    sudo cp -f arch/arm/boot/dts/exynos5422-odroidxu3-lite.dtb /media/boot
    sync

- name: Updating root ramdisk
  shell: |
    cd /tmp/
    cp .config /boot/config-$(make kernelrelease)
    update-initramfs -c -k $(make kernelrelease)
    mkimage -A arm -O linux -T ramdisk -C none -a 0 -e 0 -n uInitrd -d /boot/initrd.img-$(make kernelrelease) /boot/uInitrd-$(make kernelrelease)
    cp /boot/uInitrd-`make kernelrelease` /media/boot/uInitrd
    sync

- name: Unconditionally reboot the machine with all defaults
  reboot: