---
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['hdparm', 'vim']
      
    - name: Create a login user
      user:
        name: {{ uusername }}
        password: {{ upassword | password_hash('sha512') }}
        groups: # Empty by default, here we give it some groups
        - docker
        - sudo
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
    
    - name: add git in docker to bashrc
      lineinfile:
        path: /home/{{ uusername }}/.bashrc
        line: function git () { (docker run -ti --rm -v ${HOME}:/root -v $(pwd):/git alpine/git "$@")}    