---
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['hdparm', 'vim', 'git']
  
- name: Create a login user
  user:
    name: "{{ uusername }}"
    password: "{{ upassword | password_hash('sha512') }}"
    groups:
    - docker
    - sudo
    state: present
    shell: /bin/bash      
    system: no       
    createhome: yes     
  register: user  

- name: expose user PGID and PUID for containers
  blockinfile:
    dest: "{{ user.home }}/.bashrc"
    block: |
      export PGID="{{ user.group }}"
      export PUID="{{ user.uid }}"
    insertafter: EOF
    create: yes 

- openssh_keypair:
  become: yes
  become_method: su
  become_user: "{{ uusername }}"
    path: "{{ user.home }}/.ssh/id_rsa"

  
- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: create spindown policy for all spinning drives
  copy:
    src: 69-hdparm.rules
    dest: /etc/udev/rules.d/69-hdparm.rules