---
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['vim', 'git']
  
- name: Create a login user
  user:
    name: "{{ system_username }}"
    password: "{{ system_password | password_hash('sha512') }}"
    groups:
    - docker
    - sudo
    state: present
    shell: /bin/bash      
    createhome: yes     
  register: user  

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: expose user PGID and PUID for (docker-compose) container
  blockinfile:
    dest: "{{ user.home }}/.bashrc"
    block: |
      export PGID="{{ user.group }}"
      export PUID="{{ user.uid }}"
      export TZ="{{ timezone }}"
      export COMPOSE_OPTIONS="-e TIMEZONE=${TZ} -e PGID=${PGID} -e PUID=${PUID}"
    insertafter: EOF
    create: yes 

block: hdd

  - name: Install hdparm
    apt: name={{ item }} state=latest update_cache=yes
      loop: ['hdparm']

  - name: get path hdparm
    shell: "which hdparm"
    register: hdparm_path

  - name: Add spindown policy
    template:
      src:  69-hdparm.rules.tmpl
      dest: /etc/udev/rules.d/69-hdparm.rules

when: {{ hdd_usage }} == true