---
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: ['hdparm', 'vim', 'git']
  
- name: Create a login user
  user:
    name: "{{ uusername }}"
    password: "{{ upassword | password_hash('sha512') }}"
    groups:
    - docker
    - sudo
    state: present
    shell: /bin/bash      
    system: no       
    createhome: yes     
  register: user  

- name: expose user PGID and PUID for containers
  blockinfile:
    dest: "{{ user.home }}/.bashrc"
    block: |
      export PGID="{{ user.group }}"
      export PUID="{{ user.uid }}"
    insertbefore: BOF
    create: yes 
  
- name: Set timezone
  timezone:
    name: "{{ timezone }}"