version: '2'

services:
 transmission:
  image: haugene/transmission-openvpn:latest-armhf
  cap_add:
    - NET_ADMIN
  devices:
    - "/dev/net/tun"
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /mnt/transmission:/torrents
    - /mnt/cache/transmission/data/:/data
    - /mnt/cache/transmission/.
    - /incomplete/:/incomplete
  environment:
    - OPENVPN_PROVIDER=windscribe
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=192.168.0.0/24
    - TRANSMISSION_DOWNLOAD_DIR=/torrents
    - TRANSMISSION_INCOMPLETE_DIR=/incomplete
    - TRANSMSSION_INCOMPLETE_DIR_ENABLED=true
    - TRANSMISSION_IDLE_SEEDING_LIMIT=10
    - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
    - TRANSMISSION_RATIO_LIMIT_ENABLED=true
    - TRANSMISSION_RATIO_LIMIT=2.0  
    - TRANSMISSION_TRASH_ORIGINAL_TORRENT_FILES=true
    - PUID=1003
    - PGID=1003
 proxy:
  image: haugene/transmission-openvpn-proxy:latest-armhf
  links:
    - transmission
  ports:
    - "8585:8080"
  volumes:
    - /etc/localtime:/etc/localtime:ro

# rss:
#  image: haugene/transmission-rss:latest-armhf
#  links:
#    - transmission
#  environment:
#    - RSS_URL=http://.../xxxxx.rss
