nfs-server:
  image: gists/nfs-server
  container_name: nfs-server
  ports:
    - "2049:2049"
  cap_add:
    - SYS_ADMIN
    - SETPCAP
  environment:
    - "NFS_OPTION=ro,fsid=0"
    # - "NFS_DOMAIN=ip" # The visitor IP range
  volumes:
    - /mnt/transmission:/nfs-share
  restart: always
