---
- name: find
  lineinfile: 
    dest: /home/{{ system_username }}/.ssh/authorized_keys
    line: "managed by ssh-key-sync"
  check_mode: yes
  register: presence

- fail:
    msg: "No github keys inserted into authorized keys, continuing will result in being locked out"
  when: presence.changed

#https://github.com/vitalk/ansible-secure-ssh/tree/master

- name: Disable empty password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"

- name: Disable remote root login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"

- name: Disable password login
  lineinfile: dest={{ sshd_config }} regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"

- name: Enable PAM
  lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"
  notify: restart sshd