---
#https://github.com/vitalk/ansible-secure-ssh/tree/master
- name: Add identity key to authorized keys on host
  authorized_key:
    user: "{{ uusername }}"
    state: present
    key: '{{ item }}'
  register: add_identity_key
  with_fileglob:
    - public_keys/*

- name: Disable empty password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"

- name: Disable remote root login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"

- name: Disable password login
  lineinfile: dest={{ sshd_config }} regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"
  when: add_identity_key is succeeded and not add_identity_key is skipped

- name: Enable PAM
  lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"
  notify: restart sshd