---
- name: Create a ext4 filesystem on /dev/sda
  filesystem:
    fstype: ext4
    dev: /dev/sdb1
    force: yes

- name: Create a ext4 filesystem on /dev/sdb
  filesystem:
    fstype: ext4
    dev: /dev/sdb2
    force: yes