 - name: bootstrap docker
   shell: curl -s get.docker.io | bash

- name: configure docker partition
  mount:
    path: /var/lib/docker
    src: "{{ docker_partition }}"
    fstype: ext4
    state: present
  when: docker_partition is defined

- name: Generate docker config json
  template:
    src:  files/daemon.json.tmpl
    dest: /etc/docker/daemon.json
