- hosts: all
  become: true

  roles:
    - docker
    - common
    - sshd
    - sshkey-sync

  tasks:
    - name: Cleanup
      command: rm -rf /tmp/* 
    
    - name: Cleanup
      command: rm -rf /tmp/**/
