version: '3.7'
services:
  minidlna-server:
    restart: always
    image: forumi0721alpinearmhf/alpine-armhf-minidlna:latest
    ports: 
     - 8200
    volumes:
     - /mnt/transmission:/data:ro
    environment:
     - FRIENDLY_NAME="DLNA server"
     - MEDIA_DIR=/data
    networks:
     - traefik 
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.traefik_http.rule=Host(`dlna.maxgeheugentrainer.com`)"
       #- "traefik.http.routers.traefik_http.entrypoints=http"
       #- "traefik.http.routers.traefik_http.middlewares=http-chain@file"
     - "traefik.http.routers.traefik_https.rule=Host(`dlna.maxgeheugentrainer.com`)"
       #- "traefik.http.routers.traefik_https.entrypoints=https"
       # - "traefik.http.routers.traefik_https.middlewares=https-basicauth-chain@file"
     - "traefik.http.routers.traefik_https.tls=true"
     - "traefik.http.routers.traefik_https.tls.certresolver=letsencrypt"
     - "traefik.http.routers.traefik_https.tls.domains[0].main=*.maxgeheugentrainer.com"
       # - "traefik.http.routers.traefik_https.tls.domains[0].sans=*.maxgeheugentrainer.com"
     - "traefik.http.routers.traefik_https.service=traefik_https"
       # - "traefik.http.services.traefik_https.loadbalancer.server.port=8080"
       #- "traefik.http.services.traefik_https.loadbalancer.server.scheme=http"

networks:
   traefik:
    external: true
