version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    domainname: docker
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8181:80/tcp"
      - "4443:443/tcp"
    environment:
      - TZ='Europe/Amsterdam'
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pi.hole
      - ServerIP=192.168.178.10
      - DNS1=1.0.0.1
      - DNS2=1.1.1.1
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    #labels:
      # - "traefik.enable=true"
      #- "traefik.backend=pihole"
      #- "traefik.port=80"
      #- "traefik.frontend.rule=HostRegexp:pihole.home.maxgeheugentrainer.com"
      #- "traefik.frontend.priority=1"
      #- traefik.frontend.headers.SSLRedirect=true
      #- traefik.frontend.headers.STSSeconds=315360000
      #- traefik.frontend.headers.browserXSSFilter=true
      #- traefik.frontend.headers.contentTypeNosniff=true
      #- traefik.frontend.headers.forceSTSHeader=true
      #- traefik.frontend.headers.SSLHost=home.maxgeheugentrainer.com
      # - traefik.frontend.headers.STSIncludeSubdomains=true
      #- traefik.frontend.headers.STSPreload=true
      #- traefik.frontend.headers.frameDeny=true
    depends_on:
      - dhcphelper
    networks:
      backend:
        ipv4_address: '172.31.0.100'
      frontproxy_proxy-tier: {}

  dhcphelper:
    build: ./dhcp-helper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.100
    cap_add:
      - NET_ADMIN         

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
  frontproxy_proxy-tier:
    external: true
